### PR TITLE
test `collate_request` w batch_timeout and batch_size

### PR DESCRIPTION
**Pull request by aniketmaurya**
<details>
  <summary><b>Before submitting</b></summary>

- [ ] Was this discussed/agreed via a Github issue? (no need for typos and docs improvements)
- [ ] Did you read the [contributor guideline](https://github.com/Lightning-AI/pytorch-lightning/blob/main/.github/CONTRIBUTING.md), Pull Request section?
- [ ] Did you make sure to update the docs?
- [ ] Did you write any new necessary tests?

</details>

## What does this PR do?

Fixes the `collate_request` function to handle `batch_timeout=0`, right now it is not able to return requests from the queue. 

### Before
Test fails for the case when `batch_timeout=0`, `collate_request` didn't return any item from the queue. 

image

### After 
image

## PR review

Anyone in the community is free to review the PR once the tests have passed.
If we didn't discuss your PR in GitHub issues there's a high chance it will not be merged.

## Did you have fun?

Make sure you had fun coding 🙃

### CODE REVIEW

**Comment by aniketmaurya** [comment]
Our test fails in case of `batch_timeout=0`

**Comment by aniketmaurya** [comment]
added a fix to handle `batch_timeout=0`

**Comment by williamFalcon** [comment]
nice job @aniketmaurya. great format. let's formalize it in our template.

**Review by lantiga — COMMENTED** [review]
Looks good, I agree with keeping the loops separate so it's more readable

**Pull request merged**
