### PR TITLE
fix: kill process

### LINKED ISSUE #121: during manual local testing, the processes are not killed if the test fails
We need to terminate the processes if test fails for whatsoever reason:

## Current
```python
def test_e2e_default_batching(killall):
    process = subprocess.Popen(
        ["python", "tests/e2e/default_batching.py"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        stdin=subprocess.DEVNULL,
    )

    time.sleep(5)
    resp = requests.post("http://127.0.0.1:8000/predict", json={"input": 4.0}, headers=None)
    assert resp.status_code == 200, f"Expected response to be 200 but got {resp.status_code}"
    assert resp.json() == {"output": 16.0}, "tests/simple_server.py didn't return expected output"
    killall(process)
```

## Proposed

```py
def test_e2e_default_batching(killall):
    process = subprocess.Popen(
        ["python", "tests/e2e/default_batching.py"],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
        stdin=subprocess.DEVNULL,
    )

    time.sleep(5)
    try:
      resp = requests.post("http://127.0.0.1:8000/predict", json={"input": 4.0}, headers=None)
      assert resp.status_code == 200, f"Expected response to be 200 but got {resp.status_code}"
      assert resp.json() == {"output": 16.0}, "tests/simple_server.py didn't return expected output"
  except Exception as e:
    raise e
  finally:  # kill the process before raising the exception
    killall(process)
```

---
_Originally posted by @bhimrazy in https://github.com/Lightning-AI/LitServe/issues/119#issuecomment-2141734005_

### PR DESCRIPTION
**Pull request by bhimrazy**
## What does this PR do?

Fixes #121.

### CODE REVIEW

**Review by lantiga — COMMENTED** [review]
Great! This was super annoying.

We should consider using a decorator to make it easier to write tests this way: https://stackoverflow.com/questions/43937748/wrap-each-pytest-test-function-into-try-except

**Comment by lantiga** [comment]
Taking this for a spin and merging in a few mins : )

**Comment by lantiga** [comment]
Hey @bhimrazy simplified the solution, can you try out the last commits and see if everything checks out?

**Comment by bhimrazy** [comment]
> Hey @bhimrazy simplified the solution, can you try out the last commits and see if everything checks out?

Sure, @lantiga.

Thanks for the solution. I went through the decorator implementation but got stuck trying to kill the process.

 It seems we have a better and more simplified solution now.
 Thanks again.

**Comment by bhimrazy** [comment]
Hi @lantiga,

One of the test cases was failing because the `openai_request_data` from the fixture was not being passed properly through the decorator-wrapper.

After adding `@wraps` to the wrapper, it seems the issue is fixed.

```
@wraps(test_fn)
def wrapper(*args, **kwargs):
```

I think pytest was probably using some of the metadata from the original function.

**Review by lantiga — APPROVED** [review]
Great, ship it!

**Pull request merged**
